/* DO NOT EDIT THIS FILE - it is machine generated
 * 不要编辑这个文件——它是机器生成的。
 * JNIHelper.class javah命令生成h文件 cmd
 * build\intermediates\classes\debug> javah -jni com.sfan.jni.JNIHelper
 * */
#include <jni.h>
/* Header for class com_sfan_jni_JNIHelper */

#ifndef _Included_com_sfan_jni_JNIHelper
#define _Included_com_sfan_jni_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sfan_jni_JNIHelper
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 * TODO:      返回一个字符串
 */
JNIEXPORT jstring JNICALL Java_com_sfan_jni_JNIHelper_getMsg
        (JNIEnv *, jclass);

/*
 * Class:     com_sfan_jni_JNIHelper
 * Method:    setMsg
 * Signature: (Ljava/lang/String;)V
 * TODO:      传入一个字符串
 */
JNIEXPORT void JNICALL Java_com_sfan_jni_JNIHelper_setMsg
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
